#!/bin/bash
# delete existing build & set up the folder
rm -rf dist
mkdir dist
cp -r src/* dist

# compile
echo '[amethyst-build] compiling'
npx tsc -p ./

# remove leftover typescript files
echo '[amethyst-build] cleaning'
cd dist
find . -name '*.js.map' -type f -delete

echo '[amethyst-build] done'
