#!/bin/bash
# delete existing build & set up the folder
rm -rf dist
mkdir dist
cp -r src/* dist

# compile
echo '[ametrine-build] compiling'
tsc -p ./

# remove leftover typescript files
echo '[ametrine-build] cleaning'
cd dist
find . -name '*.js.map' -type f -delete

echo '[ametrine-build] done'
