#!/bin/bash
# check if the package is installed on system
packages=("nodejs" "nginx")
prefix="sudo"
ah_check() {
  [ -x "$(command -v $1)" ]
}

# install packages with provided package manager
ah_install() {
  for package in ${packages[@]}; do
    $prefix $1 $package
  done
}

echo "[ametrine] installing"
# get needed packages if they are not installed
if ah_check apt-get ; then ah_install "apt-get install"
elif ah_check pacman; then ah_install "pacman -S"
elif ah_check yum   ; then ah_install "yum install"
elif ah_check apk   ; then ah_install "apk add"
elif ah_check apt   ; then ah_install "apt install"
elif ah_check pkg   ; then ah_install "pkg install"
else
  echo "[ametrine] no supported package manager found"
  exit 1
fi

# get all npm packages
npm install

# make needed directories
mkdir dist

